module.exports = {
    infoMain:{
    location:'Incheon, South Korea',
    languages:[['English','Advanced','european romance language'],['Korean','Native','asian language'],['French','DELF B1','european romance language'],['Chinese','HSK 4','asian language'],['Japanese','JLPT N2','asian language'],['Spanish','Intermediate','european romance language']],
    programs:[
      ['Node.js', '/dist/logo_node.png','backend'],
      ['React.js','/dist/logo_react.png','frontend'],
      ['Vue.js','/dist/logo_vue.png','frontend'],
      ['Webpack','/dist/logo_webpack.jpg','frontend'],
      ['Babel','/dist/logo_babel.png','misc frontend'],
      ['Express.js','/dist/logo_express.png','backend'],
      ['Linux(CentOS)','/dist/logo_centos.png','backend'],
      ['PostgreSQL','/dist/logo_postgresql.png','database backend'],
      ['MySQL','/dist/logo_mysql.png','database backend'],
      ['Python','/dist/logo_python.png','backend misc'],
      ['MongoDB','/dist/logo_mongodb.png','database backend'],
      ['JQuery','/dist/logo_jquery.png','frontend'],
      ['SASS','/dist/logo_sass.png','misc'],
      ['Yarn','/dist/logo_yarn.png','misc'],
      ['Phantom.js','/dist/logo_phantomjs.png', 'web scraping'],
      ['Casper.js','/dist/logo_casperjs.png','web scraping'],
      ['Adobe Photoshop','/dist/logo_photoshop.png','graphics'],
      ['Adobe Illustrator','/dist/logo_illustrator.png', 'graphics'],
      ['Adobe After Effects','/dist/logo_aftereffects.png', 'graphics'],
      ['php','/dist/logo_php.png','backend']
    ]
  },
  infoWorks:[
    {year:'2018',title:'Stellar Marina Hotel',photo:'/dist/work_stellar.jpg',
    content:'My first commercial hotel site project.\nPostgreSQL + React(Admin Page) + JQuery + Node.js\npromotion management and reservation are fully implemented.\nlightweight, minimalistic design',
    href:'http://hotelstellar.herokuapp.com'},
    {year:'2018',title:'Korean Buzzword Crawler',photo:'/dist/work_crawler.jpg',
    content:'The app lists popular buzzwords among big Korean communities,\nranks them according to its usage rate.', href:'https://crawlerkor.herokuapp.com'},
    {year:'2017',title:'Infographic series 1',photo:'/dist/work_infographic1.jpg',
    content:'Photoshop + Illustrator, inforgraphic on human evolution', href:'http://www.todayhumor.co.kr/board/view.php?table=humorbest&no=1409045'},
    {year:'2017',title:'Infographic series 2',photo:'/dist/work_infographic2.jpg',
    content:'Photoshop + Illustrator, inforgraphic on the planet Saturn', href:'http://www.todayhumor.co.kr/board/view.php?table=humorbest&no=1295677'},
    {year:'2017',title:'Infographic series 3',photo:'/dist/work_infographic3.jpg',
    content:'Photoshop + Illustrator, inforgraphic on human evoluation', href:'http://www.todayhumor.co.kr/board/view.php?table=humorbest&no=1322230'},
    {year:'2017',title:'Logo designs',photo:'/dist/work_logo.jpg',
    content:'Logo designs for an accessory brand', href:'/'},
    {year:'2017',title:'Marketing designs',photo:'/dist/work_marketing.jpg',
    content:'Marketing pitch designs for an accessory brand', href:'/'},
    {year:'2017',title:'Interactive Infographic',photo:'/dist/work_wage.jpg',
    content:'Interactive infographic utilizing JQuery + Graph js plugin', href:'https://rabelais88.github.io/'},
  ]
}