module.exports = {
  apikeys:{
    facebook:'',
    twitter:'http://twitter.com/ParkWebdev',
    instagram:'',
    instagramId:'4101873'
  },
  gmailauth:{
    user:'',
    pass:''
  },
  pgsqlauth:{
    host:'localhost',
    port:5432,
    database:'',
    user:'',
    password:''
  },
  contactEmail:'sungryeolp@gmail.com',
  maxString:120,
  enableScrape:false,
  fbMaxRequest:20,
  igMaxRequest:10,
  dbMaxHistory:50,
  fetchIntervalMinute:180,
  infoMain:{
    location:'Incheon, South Korea',
    languages:[['English','Advanced'],['Korean','Native'],['French','DELF B1'],['Chinese','HSK B1'],['Japanese','JLPT N2'],['Spanish','Intermediate']],
    programs:[
      ['Node.js', '/dist/logo_node.png'],
      ['React.js','/dist/logo_react.png'],
      ['Vue.js','/dist/logo_vue.png'],
      ['Webpack','/dist/logo_webpack.jpg'],
      ['Babel','/dist/logo_babel.png'],
      ['Express.js','/dist/logo_express.png'],
      ['Linux(CentOS)','/dist/logo_centos.png'],
      ['PostgreSQL','/dist/logo_postgresql.png'],
      ['MySQL','/dist/logo_mysql.png'],
      ['Python','/dist/logo_python.png'],
      ['MongoDB','/dist/logo_mongodb.png'],
      ['JQuery','/dist/logo_jquery.png'],
      ['SASS','/dist/logo_sass.png'],
      ['Yarn','/dist/logo_yarn.png'],
      ['Phantom.js','/dist/logo_phantomjs.png'],
      ['Casper.js','/dist/logo_casperjs.png'],
      ['Adobe Photoshop','/dist/logo_photoshop.png'],
      ['Adobe Illustrator','/dist/logo_illustrator.png'],
      ['Adobe After Effects','/dist/logo_aftereffects.png'],
    ]
  },
  infoWorks:[
    {year:'2018',title:'Stellar Marina Hotel',photo:'/dist/work_stellar.jpg',
    content:'My first commercial hotel site project.\nPostgreSQL + React(Admin Page) + JQuery + Node.js\npromotion management and reservation are fully implemented.\nlightweight, minimalistic design',
    href:'/'},
    {year:'2018',title:'Korean Buzzword Crawler',photo:'/dist/work_crawler.jpg',
    content:'The app lists popular buzzwords among big Korean communities,\nranks them according to its usage rate.', href:'https://crawlerkor.herokuapp.com'},
    {year:'2017',title:'Infographic series 1',photo:'/dist/work_infographic1.jpg',
    content:'Photoshop + Illustrator, inforgraphic on human evolution', href:'/'},
    {year:'2017',title:'Infographic series 2',photo:'/dist/work_infographic2.jpg',
    content:'Photoshop + Illustrator, inforgraphic on the planet Saturn', href:'/'},
    {year:'2017',title:'Infographic series 3',photo:'/dist/work_infographic3.jpg',
    content:'Photoshop + Illustrator, inforgraphic on human evoluation', href:'/'},
    {year:'2017',title:'Logo designs',photo:'/dist/work_logo.jpg',
    content:'Logo designs for an accessory brand', href:'/'},
    {year:'2017',title:'Marketing designs',photo:'/dist/work_marketing.jpg',
    content:'Marketing pitch designs for an accessory brand', href:'/'},
    {year:'2017',title:'Interactive Infographic',photo:'/dist/work_wage.jpg',
    content:'Interactive infographic utilizing JQuery + Graph js plugin', href:'https://rabelais88.github.io/'},
  ]
}