module.exports = {
  apikeys:{
    facebook:'',
    twitter:'http://twitter.com/ParkWebdev',
    instagram:'',
    instagramId:'4101873'
  },
  gmailauth:{
    user:'',
    pass:''
  },
  pgsqlauth:{
    host:'localhost',
    port:5432,
    database:'',
    user:'',
    password:''
  },
  contactEmail:'sungryeolp@gmail.com',
  maxString:120,
  enableScrape:false,
  fbMaxRequest:20,
  igMaxRequest:10,
  dbMaxHistory:10,
  fetchIntervalMinute:180
}